# Generated by Django 2.2.1 on 2019-06-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('matricula', models.CharField(blank=True, max_length=120, null=True)),
                ('generacion_tsu', models.IntegerField(blank=True, null=True)),
                ('generacion_ing', models.IntegerField(blank=True, null=True)),
                ('cuatrimestre', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('cuatrimestre', models.IntegerField()),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Año*')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Materia*')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo_calificacion',
                'verbose_name_plural': 'Tipos_calificacion',
            },
        ),
        migrations.CreateModel(
            name='Tipo_movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo_movimiento',
                'verbose_name_plural': 'Tipos_movimiento',
            },
        ),
        migrations.CreateModel(
            name='Tipo_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo_status',
                'verbose_name_plural': 'Tipos_status',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Alumno')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Carreras', verbose_name='Carrera')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Grupo')),
                ('id_tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Tipo_movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.IntegerField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Carreras', verbose_name='Carrera')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Grupo')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Materia', verbose_name='Materia')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Profesor')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Alumno')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Horario')),
                ('id_tipo_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Tipo_calificacion', verbose_name='Tipo de Calificación')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_tsu', to='indicadores.Carreras', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera_ing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrera_ing', to='indicadores.Carreras'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Grupo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_status_ing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_ing', to='indicadores.Tipo_status'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_status_tsu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_tsu', to='indicadores.Tipo_status'),
        ),
    ]
